CREATE TABLE IF NOT EXISTS "exercise_template" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "exercise_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"title" text,
	"description" text,
	"tag" text,
	"questionnaire" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
ALTER TABLE "analytics_login_events" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "apps_poll" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "apps_poll_option" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "apps_poll_submission" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "community_answer" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "community_question" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_newsfeed" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_newsfeed_comment" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lesson_section" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "exercise" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "group" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "group_attendance" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "groupmember" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lesson" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lesson_comment" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lesson_completion" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lesson_language" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lesson_language_history" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "option" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organization" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organization_contacts" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organization_emaillist" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organization_plan" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organizationmember" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profile" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question_answer" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question_type" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "quiz" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "quiz_play" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "role" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "submission" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "submissionstatus" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lesson_section" RENAME TO "course_section";--> statement-breakpoint
ALTER TABLE "course_newsfeed_comment" DROP CONSTRAINT "course_newsfeed_comment_id_key";--> statement-breakpoint
ALTER TABLE "lesson" DROP CONSTRAINT "public_lesson_section_id_fkey";
--> statement-breakpoint
ALTER TABLE "course_section" DROP CONSTRAINT "public_lesson_section_course_id_fkey";
--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "id" SET DATA TYPE uuid USING id::uuid;--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "analytics_login_events" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "community_answer" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "course" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "exercise" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "group" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "groupmember" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "lesson" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "option" ALTER COLUMN "value" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "organization" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "question" ALTER COLUMN "name" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "quiz" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "submission" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "id" SET DATA TYPE uuid USING id::uuid;--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "exercise" ADD COLUMN "course_id" uuid;--> statement-breakpoint
ALTER TABLE "exercise" ADD COLUMN "section_id" uuid;--> statement-breakpoint
ALTER TABLE "exercise" ADD COLUMN "order" bigint;--> statement-breakpoint
ALTER TABLE "exercise" ADD COLUMN "is_unlocked" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "exercise" ADD CONSTRAINT "exercise_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exercise" ADD CONSTRAINT "exercise_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "public"."course_section"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson" ADD CONSTRAINT "public_course_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "public"."course_section"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "course_section" ADD CONSTRAINT "public_course_section_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."course"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "course" DROP COLUMN "version";--> statement-breakpoint
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON "analytics_login_events" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Users can insert their own login events" ON "analytics_login_events" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Delete only your own poll" ON "apps_poll" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Update only your own" ON "apps_poll" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to INSERT" ON "apps_poll" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be course member to SELECT" ON "apps_poll" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to INSERT" ON "apps_poll_option" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to UPDATE" ON "apps_poll_option" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a teacher to DELETE" ON "apps_poll_option" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be course member to SELECT" ON "apps_poll_option" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Authenticated users can read" ON "apps_poll_submission" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Delete your own submission" ON "apps_poll_submission" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "apps_poll_submission" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Update your own submission" ON "apps_poll_submission" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Authenticated users can SELECT" ON "community_answer" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Delete your own answer" ON "community_answer" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "community_answer" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Update your own answer" ON "community_answer" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Authenticated users can SELECT" ON "community_question" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Delete your own question" ON "community_question" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "community_question" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Update your own question" ON "community_question" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable access to all users if PUBLIC or to course members when " ON "course" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "course" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "course" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "course" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Delete your own comment" ON "course_newsfeed" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Update only your own" ON "course_newsfeed" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to INSERT" ON "course_newsfeed" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to SELECT" ON "course_newsfeed" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Delete your own" ON "course_newsfeed_comment" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Update only your own" ON "course_newsfeed_comment" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to INSERT" ON "course_newsfeed_comment" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to SELECT" ON "course_newsfeed_comment" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "exercise" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "exercise" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "exercise" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "exercise" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "group" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "group" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Only org admins can delete" ON "group" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Only org admins can update" ON "group" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to INSERT" ON "group_attendance" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to SELECT" ON "group_attendance" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to UPDATE" ON "group_attendance" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "group_attendance" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "groupmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "groupmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "groupmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "groupmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "lesson" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "lesson" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "lesson" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "lesson" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Delete only your own comment" ON "lesson_comment" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "lesson_comment" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Update only your own" ON "lesson_comment" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be in course group to INSERT" ON "lesson_comment" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "lesson_completion" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an course member or Admin to perform ALL operation" ON "lesson_completion" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "lesson_completion" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "lesson_completion" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "lesson_language" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "lesson_language" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "lesson_language" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "lesson_language" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Authenticated users can SELECT" ON "lesson_language_history" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "lesson_language_history" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "lesson_language_history" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "lesson_language_history" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "course_section" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "course_section" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "course_section" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "course_section" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Allow authenticated users to SELECT" ON "option" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "option" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "option" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "option" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Authenticated users can delete" ON "organization" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "organization" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "organization" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be admin to UPDATE" ON "organization" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "organization_contacts" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "organization_emaillist" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "organization_plan" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "organization_plan" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "organization_plan" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "organization_plan" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Allow authenticated users to read." ON "organizationmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "organizationmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Only admin can delete" ON "organizationmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Only admin can update" ON "organizationmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Only user can update their account via email" ON "organizationmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an admin to INSERT or allow if no existing member" ON "organizationmember" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Only auth users can read profile" ON "profile" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON "profile" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User can only delete their profiles" ON "profile" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Users can insert their own profile." ON "profile" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Users can update own profile." ON "profile" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Allow authenticated users to SELECT" ON "question" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to DELETE" ON "question" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to INSERT" ON "question" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an org member to UPDATE" ON "question" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Only authenticated users can select." ON "question_answer" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an course member to DELETE" ON "question_answer" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an course member to INSERT" ON "question_answer" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be an course member to UPDATE" ON "question_answer" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "question_type" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Authenticated users can SELECT" ON "quiz" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Authenticated users can SELECT" ON "quiz_play" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable read access for all users" ON "role" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Only authenticated users can SELECT" ON "submission" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to DELETE" ON "submission" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to INSERT" ON "submission" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "User must be a course member to UPDATE" ON "submission" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Authenticated users can SELECT" ON "submissionstatus" CASCADE;--> statement-breakpoint
DROP TYPE "public"."COURSE_VERSION";
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('group_attendance', 'id'), COALESCE((SELECT MAX(id) FROM group_attendance), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('currency', 'id'), COALESCE((SELECT MAX(id) FROM currency), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('apps_poll_option', 'id'), COALESCE((SELECT MAX(id) FROM apps_poll_option), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('option', 'id'), COALESCE((SELECT MAX(id) FROM option), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('quiz_play', 'id'), COALESCE((SELECT MAX(id) FROM quiz_play), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('organization_contacts', 'id'), COALESCE((SELECT MAX(id) FROM organization_contacts), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('lesson_comment', 'id'), COALESCE((SELECT MAX(id) FROM lesson_comment), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('submissionstatus', 'id'), COALESCE((SELECT MAX(id) FROM submissionstatus), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('video_transcripts', 'id'), COALESCE((SELECT MAX(id) FROM video_transcripts), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('organization_emaillist', 'id'), COALESCE((SELECT MAX(id) FROM organization_emaillist), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('apps_poll_submission', 'id'), COALESCE((SELECT MAX(id) FROM apps_poll_submission), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('lesson_completion', 'id'), COALESCE((SELECT MAX(id) FROM lesson_completion), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('community_question', 'id'), COALESCE((SELECT MAX(id) FROM community_question), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('course_newsfeed_comment', 'id'), COALESCE((SELECT MAX(id) FROM course_newsfeed_comment), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('organization_plan', 'id'), COALESCE((SELECT MAX(id) FROM organization_plan), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('lesson_language', 'id'), COALESCE((SELECT MAX(id) FROM lesson_language), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('lesson_language_history', 'id'), COALESCE((SELECT MAX(id) FROM lesson_language_history), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('organizationmember', 'id'), COALESCE((SELECT MAX(id) FROM organizationmember), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('question', 'id'), COALESCE((SELECT MAX(id) FROM question), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('question_answer', 'id'), COALESCE((SELECT MAX(id) FROM question_answer), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('question_type', 'id'), COALESCE((SELECT MAX(id) FROM question_type), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('role', 'id'), COALESCE((SELECT MAX(id) FROM role), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('waitinglist', 'id'), COALESCE((SELECT MAX(id) FROM waitinglist), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('test_tenant', 'id'), COALESCE((SELECT MAX(id) FROM test_tenant), 1), true);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('exercise_template', 'id'), COALESCE((SELECT MAX(id) FROM exercise_template), 1), true);