CREATE TYPE "public"."EARLY_ADOPTER_CLAIM_STATUS" AS ENUM('pending', 'claimed', 'canceled');--> statement-breakpoint
CREATE TABLE "early_adopter_claim" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "early_adopter_claim_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"polar_subscription_id" text NOT NULL,
	"polar_customer_id" text,
	"polar_checkout_id" text,
	"email" text NOT NULL,
	"status" "EARLY_ADOPTER_CLAIM_STATUS" DEFAULT 'pending' NOT NULL,
	"claimed_org_id" uuid,
	"claimed_by_profile_id" uuid,
	"expires_at" timestamp with time zone NOT NULL,
	"reminder_sent_at" timestamp with time zone,
	"payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"claimed_at" timestamp with time zone,
	CONSTRAINT "early_adopter_claim_token_hash_key" UNIQUE("token_hash"),
	CONSTRAINT "early_adopter_claim_polar_subscription_id_key" UNIQUE("polar_subscription_id")
);
--> statement-breakpoint
ALTER TABLE "early_adopter_claim" ADD CONSTRAINT "early_adopter_claim_claimed_org_id_fkey" FOREIGN KEY ("claimed_org_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "early_adopter_claim" ADD CONSTRAINT "early_adopter_claim_claimed_by_profile_id_fkey" FOREIGN KEY ("claimed_by_profile_id") REFERENCES "public"."profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_early_adopter_claim_status_created_at" ON "early_adopter_claim" USING btree ("status","created_at");