import { z } from 'zod';

// ─── Agent Roles ─────────────────────────────────────────────────────────────

export const AgentRole = {
  TEACHER: 'teacher',
  STUDENT: 'student'
} as const;

export type AgentRole = (typeof AgentRole)[keyof typeof AgentRole];

// ─── AI Provider Configuration ───────────────────────────────────────────────

export const AIProvider = {
  OPENAI: 'openai',
  ANTHROPIC: 'anthropic',
  GOOGLE: 'google',
  MOONSHOT: 'moonshot'
} as const;

export type AIProvider = (typeof AIProvider)[keyof typeof AIProvider];

export interface AIProviderConfig {
  provider: AIProvider;
  apiKey: string;
  model?: string;
}

// ─── Agent Context (passed with each chat message) ───────────────────────────

export interface AgentContext {
  orgId: string;
  courseId: string;
  courseTitle: string;
  courseDescription?: string;
  userId: string;
  role: AgentRole;
  locale: string;
  lessonId?: string;
  lessonTitle?: string;
  lessonContent?: string;
  exerciseId?: string;
  exerciseTitle?: string;
  documentId?: string;
  documentText?: string;
  existingSectionCount?: number;
}

// ─── Course Plan (generated by the agent in Plan Mode) ───────────────────────

export const CoursePlanItemSchema = z.object({
  type: z.enum(['lesson', 'exercise']).describe("'lesson' for content lessons, 'exercise' for quizzes/assessments"),
  title: z.string().min(1),
  description: z.string().min(1),
  order: z.number().int().min(0),
  hasExercise: z
    .boolean()
    .default(false)
    .describe('Only for lessons: whether to also create an exercise linked to this lesson')
});

export const CoursePlanSectionSchema = z.object({
  title: z.string().min(1),
  order: z.number().int().min(0),
  items: z
    .array(CoursePlanItemSchema)
    .min(1)
    .describe(
      'Ordered list of lessons and exercises. Use type "exercise" for standalone quizzes (e.g. end-of-section). The final course section’s items must include the comprehensive final examination exercise as specified in the course plan rules.'
    )
});

export const CoursePlanFieldsSchema = z.object({
  title: z.string().min(1),
  sections: z
    .array(CoursePlanSectionSchema)
    .min(1)
    .describe(
      'Instructional sections in teaching order, then a final section for the comprehensive course examination. The LAST section must hold the final exam (validated when the plan is submitted). Earlier sections cover the curriculum; each prior section should be represented in the exam by its own in-exercise question block with 3–5 questions when the plan is implemented.'
    )
});

/** Validated when calling `generate_course_plan` — enforces a final examination section. */
export const CoursePlanSchema = CoursePlanFieldsSchema.superRefine((plan, ctx) => {
  const lastIndex = plan.sections.length - 1;
  const lastSection = plan.sections[lastIndex];
  if (!lastSection) return;

  const hasFinalExamExercise = lastSection.items.some((item) => item.type === 'exercise');
  if (!hasFinalExamExercise) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message:
        'The last section must include at least one exercise item for the comprehensive final examination (in implementation: one exercise with create_exercise_section blocks—one per prior course section—each with 3–5 questions).',
      path: ['sections', lastIndex]
    });
  }
});

export type CoursePlanItem = z.infer<typeof CoursePlanItemSchema>;
export type CoursePlanSection = z.infer<typeof CoursePlanSectionSchema>;
export type CoursePlan = z.infer<typeof CoursePlanFieldsSchema>;

// ─── Tool Names ──────────────────────────────────────────────────────────────

export const ToolName = {
  // Read tools (shared)
  GET_COURSE_STRUCTURE: 'get_course_structure',
  GET_LESSON_CONTENT: 'get_lesson_content',
  GET_EXERCISE_DETAILS: 'get_exercise_details',
  // Write tools (teacher only)
  CREATE_SECTION: 'create_section',
  UPDATE_SECTION: 'update_section',
  CREATE_LESSON: 'create_lesson',
  UPDATE_LESSON: 'update_lesson',
  UPDATE_LESSON_CONTENT: 'update_lesson_content',
  CREATE_EXERCISE: 'create_exercise',
  CREATE_EXERCISE_SECTION: 'create_exercise_section',
  UPDATE_EXERCISE: 'update_exercise',
  UPDATE_EXERCISE_SECTION: 'update_exercise_section',
  ADD_QUESTIONS: 'add_questions',
  UPDATE_QUESTIONS: 'update_questions',
  UPDATE_COURSE_LANDING_PAGE: 'update_course_landing_page',
  CHECK_COURSE_GO_LIVE_READINESS: 'check_course_go_live_readiness',
  GO_LIVE_COURSE: 'go_live_course',
  // Agent tools
  GENERATE_COURSE_PLAN: 'generate_course_plan',
  ASK_TEMPLATE_QUESTIONS: 'ask_template_questions',
  FETCH_DOCUMENTATION_URL: 'fetch_documentation_url',
  // Student read tools (course-scoped, read-only)
  LIST_COURSE_OUTLINE: 'list_course_outline',
  READ_LESSON: 'read_lesson',
  READ_EXERCISE: 'read_exercise',
  SEARCH_COURSE: 'search_course'
} as const;

export type ToolName = (typeof ToolName)[keyof typeof ToolName];

// ─── Token Usage ─────────────────────────────────────────────────────────────

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

export interface TokenBalance {
  used: number;
  allowance: number;
  creditBalance: number;
  remaining: number;
}

// ─── Agent Status (returned by GET /agent/status) ────────────────────────────

export interface AgentTutorStatus {
  /** Whether AI tutor is enabled for this workspace. */
  enabled: boolean;
  /** Remaining tutor messages for the current learner this calendar month (only set for students). */
  capRemaining: number | null;
  /** Per-learner monthly cap value (only set for students). */
  cap: number | null;
  /** Whether cap enforcement is on in this environment (Phase 3+). */
  enforced: boolean;
}

export interface AgentStatus {
  enabled: boolean;
  role: AgentRole;
  usage: TokenBalance;
  tutor: AgentTutorStatus;
}

// ─── Document Upload ─────────────────────────────────────────────────────────

export interface DocumentUploadResult {
  documentId: string;
  fileName: string;
  mimeType: string;
  pageCount: number | null;
  wordCount: number;
  textPreview: string;
  truncated: boolean;
}

// ─── Constants ───────────────────────────────────────────────────────────────

/** Maximum characters of extracted document text to include in LLM context */
export const MAX_DOCUMENT_TEXT_LENGTH = 100_000;

/** Maximum file size for document upload (5MB) */
export const MAX_AGENT_DOCUMENT_SIZE = 5 * 1024 * 1024;

/** Redis TTL for uploaded document text (1 hour) */
export const DOCUMENT_REDIS_TTL = 3600;

/** Maximum steps per streamText() round */
export const MAX_STEPS_PER_ROUND = 15;

/** Supported MIME types for document upload */
export const SUPPORTED_DOCUMENT_TYPES = [
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation'
] as const;

/** Supported file extensions for document upload */
export const SUPPORTED_DOCUMENT_EXTENSIONS = ['.pdf', '.docx', '.pptx'] as const;

/** Token cost estimation heuristics (tokens per item) */
export const TOKEN_COST_ESTIMATES = {
  SECTION_CREATE: 500,
  LESSON_CREATE_AND_CONTENT: 3000,
  EXERCISE_CREATE: 1500
} as const;
