import {
  courseNewsfeed,
  courseNewsfeedComment,
  db,
  eq,
  groupmember,
  inArray,
  organizationmember,
  and,
  sql
} from '@db/drizzle';

import type { TNewCourseNewsfeed, TNewCourseNewsfeedComment, TNewGroupmember } from '@db/types';

import { HIPAA_COURSE_ID, HIPAA_GROUP_ID, LEARNER_PROFILES, SOC2_GROUP_ID } from '@db/utils/seed/compliance';

interface SeedNewsfeedThreadsArgs {
  enterpriseOrgId: string;
}

const ENTERPRISE_STUDENT_PROFILE_ID = '4da163ef-8050-4d4b-9c9f-3e6fac802b4d';

const feedId = (n: number) => `7e000000-a000-4000-8000-0000000000${String(n).padStart(2, '0')}`;

const FEED_IDS = Array.from({ length: 12 }, (_, i) => feedId(i + 1));

/**
 * `created_at` must increase monotonically with the generated bigint `id`: the comment
 * pagination orders by id and the UI reads timestamps, so shuffled timestamps would make
 * "N more replies" appear to skip rows. One clock, consumed in insertion order.
 */
const MINUTE_MS = 60 * 1000;

function createClock(now: Date, totalRows: number) {
  let tick = 0;

  return () => new Date(now.getTime() - (totalRows - tick++) * MINUTE_MS).toISOString();
}

type Author = { groupMemberId: string; fullname: string };

function pickAuthor(authors: Author[], index: number): Author {
  return authors[(index * 7) % authors.length];
}

const PROSE = [
  'The part that keeps tripping teams up is that least privilege is a process, not a configuration. You grant the narrow role on day one, then someone needs a one-off export, and the temporary grant never gets revoked because nothing is watching it. Six months later the "narrow" role is effectively admin and nobody can point at the moment it changed.',
  'We ran the numbers on last quarter and the majority of our access findings were not people granting too much up front. They were grants that were correct when issued and never revisited. That is a review cadence problem, not a permissions model problem, and it needs an owner rather than a policy document.',
  'Worth separating two things that get conflated here. There is the question of who can reach the data, and the question of whether we would notice if they did. Most of our controls answer the first one. Almost none of them answer the second, which is why an audit finding feels like a surprise even when the access list was correct all along.'
];

const ONE_WORD = ['Agreed.', 'Same.', 'No.', 'This.', 'Exactly.', 'Noted.', 'Fair.', 'Right.'];

export async function seedNewsfeedThreads({ enterpriseOrgId }: SeedNewsfeedThreadsArgs): Promise<void> {
  // 1. Groupmember rows for the org admin and the enterprise student.
  // Without an ADMIN groupmember the admin can view the feed (via isOrgAdmin) but has no
  // group member id, so they cannot post or comment — which makes this seed unverifiable.
  const orgAdmins = await db
    .select({ profileId: organizationmember.profileId })
    .from(organizationmember)
    .where(and(eq(organizationmember.organizationId, enterpriseOrgId), eq(organizationmember.roleId, 1)));
  const adminProfileId = orgAdmins.find((admin) => admin.profileId)?.profileId ?? null;

  const staffMembers: Array<{ groupId: string; profileId: string; roleId: number }> = [];
  for (const groupId of [HIPAA_GROUP_ID, SOC2_GROUP_ID]) {
    if (adminProfileId) staffMembers.push({ groupId, profileId: adminProfileId, roleId: 1 });
    staffMembers.push({ groupId, profileId: ENTERPRISE_STUDENT_PROFILE_ID, roleId: 3 });
  }

  const existingStaff = await db
    .select({ groupId: groupmember.groupId, profileId: groupmember.profileId })
    .from(groupmember)
    .where(inArray(groupmember.groupId, [HIPAA_GROUP_ID, SOC2_GROUP_ID]));
  const existingStaffKey = new Set(existingStaff.map((m) => `${m.groupId}-${m.profileId}`));

  const newStaff: TNewGroupmember[] = staffMembers
    .filter((m) => !existingStaffKey.has(`${m.groupId}-${m.profileId}`))
    .map((m) => ({ groupId: m.groupId, profileId: m.profileId, roleId: m.roleId }));

  if (newStaff.length > 0) {
    await db.insert(groupmember).values(newStaff);
    console.log(`   ✓ Inserted ${newStaff.length} staff groupmember(s)`);
  } else {
    console.log('   ✓ Staff groupmembers already exist, skipping');
  }

  // 2. Resolve groupmember ids — authorId is a groupmember.id, generated by the database.
  const allMembers = await db
    .select({ id: groupmember.id, groupId: groupmember.groupId, profileId: groupmember.profileId })
    .from(groupmember)
    .where(eq(groupmember.groupId, HIPAA_GROUP_ID));
  const memberByProfile = new Map<string, string>();
  for (const member of allMembers) {
    if (member.profileId) memberByProfile.set(member.profileId, member.id);
  }

  const learnerAuthors: Author[] = LEARNER_PROFILES.map((profile) => ({
    groupMemberId: memberByProfile.get(profile.id) ?? '',
    fullname: profile.fullname
  })).filter((author) => author.groupMemberId);

  if (learnerAuthors.length === 0) {
    console.log('   ⚠ No HIPAA groupmembers found — run `pnpm seed --compliance` first, skipping');
    return;
  }

  const adminAuthor: Author = {
    groupMemberId: (adminProfileId && memberByProfile.get(adminProfileId)) || learnerAuthors[0].groupMemberId,
    fullname: 'Enterprise Admin'
  };

  // 3. Feeds
  const existingFeeds = await db
    .select({ id: courseNewsfeed.id })
    .from(courseNewsfeed)
    .where(inArray(courseNewsfeed.id, FEED_IDS));
  const existingFeedIds = new Set(existingFeeds.map((feed) => feed.id));

  const emptyReaction = { clap: [], smile: [], thumbsup: [], thumbsdown: [] };
  const reactedIds = learnerAuthors.slice(0, 9).map((author) => author.groupMemberId);

  const feedPlan: Array<{ id: string; content: string; authorId: string; isPinned?: boolean; reaction?: unknown }> = [
    {
      id: feedId(1),
      content: '<p>Reading the incident write-up together — thread below.</p>',
      authorId: adminAuthor.groupMemberId
    },
    {
      id: feedId(2),
      content: '<p>Quick poll: which control worries you most before the audit?</p>',
      authorId: adminAuthor.groupMemberId
    },
    {
      id: feedId(3),
      content: '<p>Long-form: why least privilege keeps failing us.</p>',
      authorId: learnerAuthors[0].groupMemberId
    },
    {
      id: feedId(4),
      content: '<p>One word answers only. Is annual retraining enough?</p>',
      authorId: learnerAuthors[1].groupMemberId
    },
    {
      id: feedId(5),
      content: '<p>The audit window is Nov 3–14. Block the time now.</p>',
      authorId: adminAuthor.groupMemberId,
      isPinned: true
    },
    {
      id: feedId(6),
      content: '<p>Slides from this morning are in the shared drive.</p>',
      authorId: adminAuthor.groupMemberId
    },
    {
      id: feedId(7),
      content: '<p>Thanks to everyone who finished the module early.</p>',
      authorId: adminAuthor.groupMemberId,
      reaction: {
        clap: reactedIds.slice(0, 5),
        smile: reactedIds.slice(5, 7),
        thumbsup: reactedIds.slice(7, 9),
        thumbsdown: []
      }
    },
    {
      id: feedId(8),
      content: '<p>Debate: is annual retraining enough, or do we need quarterly refreshers?</p>',
      authorId: learnerAuthors[2].groupMemberId
    },
    {
      id: feedId(9),
      content: '<p>Thinking out loud about our data retention defaults.</p>',
      authorId: learnerAuthors[0].groupMemberId
    },
    {
      id: feedId(10),
      content: '<p>This thread runs deeper than one page will load.</p>',
      authorId: learnerAuthors[3].groupMemberId
    },
    {
      id: feedId(11),
      content: '<p>Mixed thread: wide at the top, deep in one corner.</p>',
      authorId: adminAuthor.groupMemberId
    },
    {
      id: feedId(12),
      content: '<p>Older thread, kept for the flattened reply format.</p>',
      authorId: learnerAuthors[4].groupMemberId
    }
  ];

  const feedClock = createClock(new Date(), feedPlan.length * 60);
  const newFeeds: TNewCourseNewsfeed[] = feedPlan
    .filter((feed) => !existingFeedIds.has(feed.id))
    .map((feed) => ({
      id: feed.id,
      courseId: HIPAA_COURSE_ID,
      authorId: feed.authorId,
      content: feed.content,
      isPinned: feed.isPinned ?? false,
      reaction: (feed.reaction ?? emptyReaction) as TNewCourseNewsfeed['reaction'],
      createdAt: feedClock()
    }));

  if (newFeeds.length > 0) {
    await db.insert(courseNewsfeed).values(newFeeds);
    console.log(`   ✓ Inserted ${newFeeds.length} newsfeed post(s)`);
  } else {
    console.log('   ✓ Newsfeed posts already exist, skipping');
  }

  // 4. Comments — skip any feed that already has some, so a half-finished run resumes cleanly.
  const commentedFeeds = await db
    .select({ courseNewsfeedId: courseNewsfeedComment.courseNewsfeedId })
    .from(courseNewsfeedComment)
    .where(inArray(courseNewsfeedComment.courseNewsfeedId, FEED_IDS))
    .groupBy(courseNewsfeedComment.courseNewsfeedId);
  const alreadyCommented = new Set(commentedFeeds.map((row) => row.courseNewsfeedId));

  const clock = createClock(new Date(), 400);
  let insertedComments = 0;

  /** Inserts one level and returns the generated ids, in the order the rows were given. */
  async function insertLevel(rows: TNewCourseNewsfeedComment[]): Promise<number[]> {
    if (rows.length === 0) return [];

    const inserted = await db.insert(courseNewsfeedComment).values(rows).returning({ id: courseNewsfeedComment.id });
    insertedComments += inserted.length;

    return inserted.map((row) => row.id);
  }

  function row(feed: string, authorIndex: number, content: string, parentId: number | null): TNewCourseNewsfeedComment {
    return {
      courseNewsfeedId: feed,
      authorId: pickAuthor(learnerAuthors, authorIndex).groupMemberId,
      content,
      parentId,
      replyToCommentId: null,
      createdAt: clock()
    };
  }

  async function insertChain(feed: string, depth: number, label: (level: number) => string) {
    let parentId: number | null = null;
    for (let level = 0; level < depth; level++) {
      const [id] = await insertLevel([row(feed, level, label(level), parentId)]);
      parentId = id;
    }
    return parentId;
  }

  // 01 — linear chain 14 deep: indent cap and "Continue this thread"
  if (!alreadyCommented.has(feedId(1))) {
    await insertChain(feedId(1), 14, (level) =>
      level === 0
        ? 'Starting here so we can follow the whole argument in one place.'
        : `Following on from that — point number ${level + 1} in the chain.`
    );
  }

  // 02 — one root, 60 direct replies: "N more replies" paging and cursor correctness
  if (!alreadyCommented.has(feedId(2))) {
    const [rootId] = await insertLevel([row(feedId(2), 0, 'Drop your answer as a reply to this comment.', null)]);
    await insertLevel(
      Array.from({ length: 60 }, (_, i) =>
        row(feedId(2), i + 1, `Answer ${i + 1}: access reviews are the weak spot.`, rootId)
      )
    );
  }

  // 03 — long prose at depth: wrapping at maximum indent
  if (!alreadyCommented.has(feedId(3))) {
    for (let rootIndex = 0; rootIndex < 3; rootIndex++) {
      const [rootId] = await insertLevel([row(feedId(3), rootIndex, PROSE[rootIndex], null)]);
      const [childId] = await insertLevel([row(feedId(3), rootIndex + 3, PROSE[(rootIndex + 1) % 3], rootId)]);
      await insertLevel([row(feedId(3), rootIndex + 6, PROSE[(rootIndex + 2) % 3], childId)]);
    }
  }

  // 04 — one-word replies: dense vertical rhythm and small rail hit areas
  if (!alreadyCommented.has(feedId(4))) {
    for (let rootIndex = 0; rootIndex < 4; rootIndex++) {
      const [rootId] = await insertLevel([row(feedId(4), rootIndex, ONE_WORD[rootIndex], null)]);
      await insertLevel(
        Array.from({ length: 5 }, (_, i) =>
          row(feedId(4), rootIndex + i, ONE_WORD[(rootIndex + i) % ONE_WORD.length], rootId)
        )
      );
    }
  }

  // 05 — pinned post that also has comments
  if (!alreadyCommented.has(feedId(5))) {
    for (let rootIndex = 0; rootIndex < 2; rootIndex++) {
      const [rootId] = await insertLevel([row(feedId(5), rootIndex, 'Booked. Will the sessions be recorded?', null)]);
      await insertLevel([row(feedId(5), rootIndex + 2, 'Yes, recordings go up the same afternoon.', rootId)]);
    }
  }

  // 06 — deliberately no comments (empty state)

  // 07 — reactions only, no replies
  if (!alreadyCommented.has(feedId(7))) {
    await insertLevel(Array.from({ length: 5 }, (_, i) => row(feedId(7), i, 'Finished mine over the weekend.', null)));
  }

  // 08 — branching tree: multi-branch collapse and per-branch rails
  if (!alreadyCommented.has(feedId(8))) {
    const [rootId] = await insertLevel([
      row(feedId(8), 0, 'Annual is a floor, not a ceiling. Where do people land?', null)
    ]);
    const depthOne = await insertLevel(
      Array.from({ length: 3 }, (_, i) =>
        row(feedId(8), i + 1, `Position ${i + 1}: quarterly for anyone touching production.`, rootId)
      )
    );
    for (const [branchIndex, branchId] of depthOne.entries()) {
      const depthTwo = await insertLevel(
        Array.from({ length: 2 }, (_, i) =>
          row(feedId(8), branchIndex * 2 + i + 4, 'That only works if the refresher is short.', branchId)
        )
      );
      for (const [leafIndex, leafId] of depthTwo.entries()) {
        await insertLevel(
          Array.from({ length: 2 }, (_, i) =>
            row(
              feedId(8),
              branchIndex * 4 + leafIndex * 2 + i + 10,
              'Fifteen minutes, and it has to be role specific.',
              leafId
            )
          )
        );
      }
    }
  }

  // 09 — one author replying to themselves 8 deep
  if (!alreadyCommented.has(feedId(9))) {
    const soleAuthor = learnerAuthors[0];
    let parentId: number | null = null;
    for (let level = 0; level < 8; level++) {
      const [id] = await insertLevel([
        {
          courseNewsfeedId: feedId(9),
          authorId: soleAuthor.groupMemberId,
          content:
            level === 0
              ? 'Thinking out loud, will keep adding as I go.'
              : `Addendum ${level}: the default matters more than the policy.`,
          parentId,
          replyToCommentId: null,
          createdAt: clock()
        }
      ]);
      parentId = id;
    }
  }

  // 10 — 9 deep with siblings near the top, so depths below the fetch limit
  //      give "N more replies" a truthful nonzero count
  if (!alreadyCommented.has(feedId(10))) {
    let parentId: number | null = null;
    for (let level = 0; level < 9; level++) {
      const [id] = await insertLevel([row(feedId(10), level, `Level ${level + 1} of the deep branch.`, parentId)]);
      if (level < 4 && parentId !== null) {
        await insertLevel([row(feedId(10), level + 20, `A sibling at level ${level + 1}.`, parentId)]);
      }
      parentId = id;
    }
  }

  // 11 — realistic composite: 12 roots, one deep chain, one wide fan-out
  if (!alreadyCommented.has(feedId(11))) {
    const rootIds = await insertLevel(
      Array.from({ length: 12 }, (_, i) => row(feedId(11), i, `Top level comment ${i + 1}.`, null))
    );
    let deepParent: number | null = rootIds[2];
    for (let level = 0; level < 11; level++) {
      const [id] = await insertLevel([row(feedId(11), level + 2, `Deep corner, step ${level + 1}.`, deepParent)]);
      deepParent = id;
    }
    await insertLevel(
      Array.from({ length: 20 }, (_, i) =>
        row(feedId(11), i + 5, `Wide reply ${i + 1} under the seventh comment.`, rootIds[6])
      )
    );
  }

  // 12 — legacy shape: flat parentId with replyToCommentId pointing at a sibling
  if (!alreadyCommented.has(feedId(12))) {
    const [rootId] = await insertLevel([row(feedId(12), 0, 'Original question, kept for the old reply format.', null)]);
    const siblingIds = await insertLevel(
      Array.from({ length: 5 }, (_, i) =>
        row(feedId(12), i + 1, `Flattened reply ${i + 1}, aimed at a sibling.`, rootId)
      )
    );
    for (const [index, id] of siblingIds.entries()) {
      const target = index === 0 ? rootId : siblingIds[index - 1];
      await db.update(courseNewsfeedComment).set({ replyToCommentId: target }).where(eq(courseNewsfeedComment.id, id));
    }
  }

  if (insertedComments > 0) {
    console.log(`   ✓ Inserted ${insertedComments} newsfeed comment(s) across ${FEED_IDS.length} thread variation(s)`);
  } else {
    console.log('   ✓ Newsfeed comments already exist, skipping');
  }

  const [{ maxId }] = await db
    .select({ maxId: sql<number>`COALESCE(MAX(${courseNewsfeedComment.id}), 0)::int` })
    .from(courseNewsfeedComment);
  console.log(`   ✓ Highest newsfeed comment id is now ${Number(maxId)}`);
}
