export const QUESTION_TYPE_KEY = {
  RADIO: 'RADIO',
  CHECKBOX: 'CHECKBOX',
  TEXTAREA: 'TEXTAREA',
  TRUE_FALSE: 'TRUE_FALSE',
  SHORT_ANSWER: 'SHORT_ANSWER',
  NUMERIC: 'NUMERIC',
  FILL_BLANK: 'FILL_BLANK',
  FILE_UPLOAD: 'FILE_UPLOAD',
  MATCHING: 'MATCHING',
  ORDERING: 'ORDERING',
  HOTSPOT: 'HOTSPOT',
  LINK: 'LINK'
} as const;

export type QuestionTypeKey = (typeof QUESTION_TYPE_KEY)[keyof typeof QUESTION_TYPE_KEY];

export const LEGACY_QUESTION_TYPE_KEYS = [
  QUESTION_TYPE_KEY.RADIO,
  QUESTION_TYPE_KEY.CHECKBOX,
  QUESTION_TYPE_KEY.TEXTAREA
] as const;
