# ClassroomIO Development
# Project: Self-hosted Backend and Dashboard
# Description: Optimized development docker-compose file for self-hosting.
# Author: rotimi-best
# Date: 2024-09-18

version: '3.8'

services:
  backend:
    build:
      context: ../../apps/backend # ✅ Correct - backend is standalone
      dockerfile: Dockerfile
      target: development
      cache_from:
        - chifez4u/backend:development
        - chifez4u/backend-deps:18.18.0
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - '3002:3002'
    volumes:
      # Mount source code for hot reloading
      - ../../apps/backend/src:/app/src
      - ../../apps/backend/package.json:/app/package.json
      - ../../apps/backend/tsconfig.json:/app/tsconfig.json
      # Exclude node_modules from being overwritten
      - /app/node_modules
    env_file:
      - ../../apps/backend/.env
    environment:
      - NODE_ENV=development
      # Supabase - Database
      - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
      - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
      # Cloudflare - Video upload
      - CLOUDFLARE_BUCKET_DOMAIN=${CLOUDFLARE_BUCKET_DOMAIN}
      - CLOUDFLARE_ACCESS_KEY=${CLOUDFLARE_ACCESS_KEY}
      - CLOUDFLARE_SECRET_ACCESS_KEY=${CLOUDFLARE_SECRET_ACCESS_KEY}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_BUCKET_ID=${CLOUDFLARE_BUCKET_ID}
      # SMTP - Emails
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SENDER=${SMTP_SENDER}
    restart: unless-stopped

  dashboard:
    build:
      context: ../../
      dockerfile: apps/dashboard/Dockerfile
      target: development
      cache_from:
        - chifez4u/dashboard:development
        - chifez4u/dashboard-deps:18.18.0
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - '3000:3000'
    volumes:
      # Mount source code for hot reloading
      - ../../apps/dashboard/src:/app/apps/dashboard/src
      - ../../apps/dashboard/static:/app/apps/dashboard/static
      - ../../apps/dashboard/package.json:/app/apps/dashboard/package.json
      - ../../apps/dashboard/svelte.config.js:/app/apps/dashboard/svelte.config.js
      - ../../apps/dashboard/vite.config.js:/app/apps/dashboard/vite.config.js
      - ../../apps/dashboard/tsconfig.json:/app/apps/dashboard/tsconfig.json
      # Mount shared packages for development
      - ../../packages:/app/packages
      # Exclude node_modules from being overwritten
      - /app/node_modules
      - /app/apps/dashboard/node_modules
    env_file:
      - ../../apps/dashboard/.env
    environment:
      - IS_SELFHOSTED=true
      - DEPLOYMENT_PROVIDER=docker
      - NODE_ENV=development
      # Supabase - Database
      - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
      - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
      - PRIVATE_SUPABASE_SERVICE_ROLE=${PRIVATE_SUPABASE_SERVICE_ROLE}
      - PRIVATE_APP_HOST=${PRIVATE_APP_HOST}
      - PRIVATE_APP_SUBDOMAINS=${PRIVATE_APP_SUBDOMAINS}
      - UNSPLASH_API_KEY=${UNSPLASH_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - PUBLIC_IP_REGISTRY_KEY=${PUBLIC_IP_REGISTRY_KEY}
    depends_on:
      - backend
    restart: unless-stopped
# Remove volumes - they're not needed with the optimized approach
# Development uses bind mounts for hot reloading
