image: gitpod/workspace-full

tasks:
  - name: Setup Supabase CLI
    init: brew install supabase/tap/supabase
  - name: Start Supabase
    command: supabase start
  - name: Install required dependencies
    command: pnpm i
  - name: Run all projects (in development mode)
    command: pnpm dev
