image: gitpod/workspace-full

tasks:
  - name: Setup Supabase CLI
    init: brew install supabase/tap/supabase
    main: supabase start
  - name: Install required dependencies and run projects
    init: pnpm i
    main: pnpm dev
