import { test, expect } from '@playwright/test';

import { loginAsAdmin } from '../helpers/login';

/**
 * Reference spec for OpenCode / contributors. PR demos use ephemeral specs in
 * `.github/demo-runs/pr-<number>.spec.ts` generated by the pr-demo workflow.
 */
test('admin can sign in with test hooks', async ({ page }) => {
  await loginAsAdmin(page);
  await expect(page.getByTestId('app-sidebar-trigger')).toBeVisible();
});
