export const NAV_IDS = {
  NEWS_FEED: 'NEWS_FEED',
  LESSONS: 'LESSONS',
  ATTENDANCE: 'ATTENDANCE',
  SUBMISSIONS: 'SUBMISSIONS',
  MARKS: 'MARKS',
  COMPLIANCE: 'COMPLIANCE',
  CERTIFICATES: 'CERTIFICATES',
  LANDING_PAGE: 'LANDING_PAGE',
  PEOPLE: 'PEOPLE',
  ANALYTICS: 'ANALYTICS',
  SETTINGS: 'SETTINGS',
  SECTION: 'SECTION',
  AI_ASSISTANT: 'AI_ASSISTANT'
};

export const COURSE_SIDEBAR_DEFAULT_WIDTH = 320;
export const COURSE_SIDEBAR_MIN_WIDTH = 220;
export const COURSE_SIDEBAR_MAX_WIDTH = 420;
export const COURSE_SIDEBAR_STORAGE_KEY = 'classroomio-course-sidebar-width';
