window.LessonPreview = {
  course: {
    title: 'Modern Web Development with React',
    slug: 'modern-web-dev-react',
    description:
      'Build production React apps from scratch — components, hooks, data fetching, and a shipped capstone.',
    cost: 79,
    currency: 'USD',
    lessonCount: 24,
    exerciseCount: 8,
    duration: '12h 40m',
    rating: '4.8',
    reviewCount: 312,
    instructor: 'Jordan Diallo',
    heroLessonId: 'l1'
  },
  lessons: [
    {
      id: 'l1',
      section: 'Getting started',
      title: 'Welcome and how this course works',
      duration: '4:12',
      minutes: 4,
      kind: 'video',
      preview: true,
      hero: true,
      poster: 'linear-gradient(135deg, #1e3a8a 0%, #0ea5e9 55%, #22c55e 100%)',
      summary: 'A four-minute tour of the course, the projects you will ship, and how to get unstuck.'
    },
    {
      id: 'l2',
      section: 'Getting started',
      title: 'What you will build',
      duration: '7:48',
      minutes: 8,
      kind: 'video',
      preview: true,
      poster: 'linear-gradient(135deg, #7c3aed 0%, #ec4899 60%, #f59e0b 100%)',
      summary: 'Walk through the finished capstone: a task board with live updates and auth.'
    },
    {
      id: 'l3',
      section: 'Getting started',
      title: 'Set up your environment',
      duration: '6 min read',
      minutes: 6,
      kind: 'text',
      preview: true,
      poster: 'linear-gradient(135deg, #0f172a 0%, #334155 100%)',
      summary: 'Node, a code editor, and the starter repo — written so you can follow along offline.',
      body: [
        'This lesson is a short checklist, not a video. Preview it in full even if you have not enrolled.',
        'Install Node 20 LTS, clone the starter repository, and run pnpm install. You should see the welcome page at localhost:5173.',
        'If anything fails, the troubleshooting section at the bottom covers the three most common issues: wrong Node version, a blocked port, and a missing .env file.'
      ]
    },
    {
      id: 'l4',
      section: 'React foundations',
      title: 'Anatomy of a React component',
      duration: '3 figures',
      minutes: 5,
      kind: 'image',
      preview: true,
      poster: 'linear-gradient(135deg, #0ea5e9 0%, #6366f1 70%)',
      summary: 'Three annotated diagrams of props, state, and the render cycle.',
      figures: ['Props in, UI out', 'State lives inside the component', 'Render → commit → paint']
    },
    {
      id: 'l5',
      section: 'React foundations',
      title: 'Your first component',
      duration: '11:20',
      minutes: 11,
      kind: 'video',
      preview: false,
      poster: 'linear-gradient(135deg, #111827 0%, #1f2937 100%)',
      summary: 'Build a Button component and render it on the page.'
    },
    {
      id: 'l6',
      section: 'React foundations',
      title: 'Props and state',
      duration: '14:05',
      minutes: 14,
      kind: 'video',
      preview: false,
      poster: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)',
      summary: 'The difference between data you receive and data you own.'
    },
    {
      id: 'l7',
      section: 'React foundations',
      title: 'Lists and keys',
      duration: '9:40',
      minutes: 10,
      kind: 'video',
      preview: false,
      poster: 'linear-gradient(135deg, #14532d 0%, #166534 100%)',
      summary: 'Map over data without confusing React on re-render.'
    },
    {
      id: 'l8',
      section: 'Hooks',
      title: 'useEffect without the footguns',
      duration: '16:10',
      minutes: 16,
      kind: 'video',
      preview: false,
      poster: 'linear-gradient(135deg, #7f1d1d 0%, #b91c1c 100%)',
      summary: 'When to fetch, when not to, and how to clean up.'
    }
  ],
  copy: {
    en: {
      navCourses: 'Courses',
      navLogin: 'Log in',
      previewBadge: 'Preview',
      heroLesson: 'Hero lesson',
      morePreview: (n) => (n === 1 ? '1 more lesson to preview' : `${n} more lessons to preview`),
      previewCount: (n, total) => `${n} of ${total} lessons are free to preview`,
      enrollContinue: 'Enroll to continue',
      buyContinue: 'Buy to continue',
      enroll: 'Enroll for free',
      buy: (price) => `Buy · ${price}`,
      notAccepting: 'Not accepting enrollments',
      curriculum: 'Curriculum',
      curriculumHeading: 'What you will study',
      lockedHint: 'Enroll to unlock this lesson',
      playing: 'Now playing',
      reading: 'Reading',
      viewing: 'Viewing',
      next: 'Next preview',
      prev: 'Previous preview',
      play: 'Play preview',
      pause: 'Pause',
      enrollPromptTitle: 'Enjoying the preview?',
      enrollPromptBody: (left) =>
        left > 0
          ? `There are ${left} more preview lessons after this. Enroll to keep going.`
          : 'That was the last free preview. Enroll to unlock the rest of the course.',
      lockedPromptTitle: 'This lesson is locked',
      lockedPromptBody: 'Preview lessons are open above. Enroll to unlock the rest of the curriculum.',
      playlistTitle: 'Lessons you can preview',
      articleEyebrow: 'Lesson notes',
      figureEyebrow: 'Diagram',
      langLabel: 'Academy language',
      costLabel: 'Course cost',
      free: 'Free',
      paid: 'Paid',
      lessons: 'lessons',
      exploreTitle: 'Explore',
      exploreSub: 'Browse the catalog and preview a course before you enroll.',
      withPreview: 'Has previews',
      noPreview: 'No previews',
      close: 'Close',
      requirements: 'Requirements',
      reqBody: 'A laptop, Node 20, and curiosity. No prior React required.',
      adminPreview: 'Allow preview',
      adminHero: 'Use as hero video',
      adminHeroHelp: 'This lesson plays on the course landing page before someone enrolls.',
      adminPreviewHelp: 'Unenrolled visitors can watch or read this lesson on the landing page and in Explore.'
    },
    fr: {
      navCourses: 'Cours',
      navLogin: 'Connexion',
      previewBadge: 'Aperçu',
      heroLesson: 'Leçon à la une',
      morePreview: (n) =>
        n === 1 ? '1 leçon supplémentaire à prévisualiser' : `${n} leçons supplémentaires à prévisualiser`,
      previewCount: (n, total) => `${n} leçons sur ${total} sont en aperçu libre`,
      enrollContinue: 'Inscrivez-vous pour continuer',
      buyContinue: 'Achetez pour continuer',
      enroll: "S'inscrire gratuitement",
      buy: (price) => `Acheter · ${price}`,
      notAccepting: 'Inscriptions fermées',
      curriculum: 'Programme',
      curriculumHeading: 'Ce que vous allez étudier',
      lockedHint: 'Inscrivez-vous pour déverrouiller cette leçon',
      playing: 'En lecture',
      reading: 'Lecture',
      viewing: 'Consultation',
      next: 'Aperçu suivant',
      prev: 'Aperçu précédent',
      play: "Lire l'aperçu",
      pause: 'Pause',
      enrollPromptTitle: "L'aperçu vous plaît ?",
      enrollPromptBody: (left) =>
        left > 0
          ? `Il reste ${left} leçons en aperçu après celle-ci. Inscrivez-vous pour continuer.`
          : "C'était le dernier aperçu gratuit. Inscrivez-vous pour débloquer le reste du cours.",
      lockedPromptTitle: 'Cette leçon est verrouillée',
      lockedPromptBody:
        'Les leçons en aperçu sont ouvertes plus haut. Inscrivez-vous pour débloquer le reste du programme.',
      playlistTitle: 'Leçons en aperçu',
      articleEyebrow: 'Notes de leçon',
      figureEyebrow: 'Schéma',
      langLabel: "Langue de l'académie",
      costLabel: 'Tarif du cours',
      free: 'Gratuit',
      paid: 'Payant',
      lessons: 'leçons',
      exploreTitle: 'Explorer',
      exploreSub: 'Parcourez le catalogue et prévisualisez un cours avant de vous inscrire.',
      withPreview: 'Avec aperçus',
      noPreview: 'Sans aperçu',
      close: 'Fermer',
      requirements: 'Prérequis',
      reqBody: 'Un ordinateur, Node 20 et de la curiosité. Aucune expérience React exigée.',
      adminPreview: 'Autoriser l’aperçu',
      adminHero: 'Utiliser comme vidéo principale',
      adminHeroHelp: 'Cette leçon est lue sur la page du cours avant l’inscription.',
      adminPreviewHelp:
        'Les visiteurs non inscrits peuvent regarder ou lire cette leçon sur la page du cours et dans Explorer.'
    }
  }
};
