import type { LandingThemeVars } from '../theme-vars-base';

export const vars: LandingThemeVars = {
  '--landing-bg': '#f4f3ed',
  '--landing-bg-section': '#ebeae3',
  '--landing-card': '#fafaf5',
  '--landing-card-soft': '#ecebe5',
  '--landing-fg': '#1a1a1a',
  '--landing-fg-muted': '#76746c',
  '--landing-fg-faint': '#98968e',
  '--landing-border': '#d9d8d0',
  '--landing-border-soft': '#e3e2da',
  '--landing-accent': '#c25237',
  '--landing-accent-fg': '#fafaf5',
  '--landing-button-primary-bg': '#1a1a1a',
  '--landing-button-primary-fg': '#fafaf5',
  '--landing-button-primary-bg-hover': '#2c2b29',
  '--landing-button-secondary-bg': 'transparent',
  '--landing-button-secondary-fg': '#1a1a1a',
  '--landing-button-secondary-border': '#d9d8d0',
  '--landing-button-secondary-bg-hover': '#ebeae3',
  '--landing-button-tertiary-fg': '#c25237',
  '--landing-button-tertiary-bg-hover': '#ebeae3',
  '--landing-heading-weight': '500',
  '--landing-heading-tracking': '-0.025em',
  '--landing-heading-case': 'none',
  '--landing-eyebrow-tracking': '0.16em',
  '--landing-eyebrow-case': 'uppercase',
  '--landing-radius-card': '0px',
  '--landing-radius-pill': '9999px',
  '--landing-shadow-card': 'none',
  '--landing-divider': '1px solid color-mix(in oklab, #1a1a1a, transparent 80%)',
  '--landing-mono-family': 'ui-serif, Georgia, serif',
  '--landing-glow': 'none',
  '--landing-panel-bg-accent': 'color-mix(in oklab, #c25237, #f4f3ed 85%)'
};
