const {
  CLOUDFLARE_BUCKET_DOMAIN,
  CLOUDFLARE_ACCESS_KEY,
  CLOUDFLARE_SECRET_ACCESS_KEY,
  CLOUDFLARE_ACCOUNT_ID
} = process.env;

module.exports = {
  CLOUDFLARE: {
    CONFIGS: {
      BUCKET_DOMAIN: CLOUDFLARE_BUCKET_DOMAIN,
      ACCESS_KEY: CLOUDFLARE_ACCESS_KEY,
      SECRET_ACCESS_KEY: CLOUDFLARE_SECRET_ACCESS_KEY,
      ACCOUNT_ID: CLOUDFLARE_ACCOUNT_ID
    },
    R2: {
      BUCKET: 'videos',
      BUCKET_DOMAIN: CLOUDFLARE_ACCOUNT_ID
        ? `https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com`
        : CLOUDFLARE_BUCKET_DOMAIN
    }
  }
};
