import { defineConfig } from 'vite';
import path from 'path';
import replace from '@rollup/plugin-replace';
import { svelte } from '@sveltejs/vite-plugin-svelte';

// DON'T EDIT THIS OBJECT, IT IS AUTOMATICALLY GENERATED by `pnpm build`
const entry = {
  index: path.resolve(__dirname, './src/index.ts'),
  button: path.resolve(__dirname, './src/base/button/index.ts'),
  'dropdown-menu': path.resolve(__dirname, './src/base/dropdown-menu/index.ts'),
  input: path.resolve(__dirname, './src/base/input/index.ts'),
  popover: path.resolve(__dirname, './src/base/popover/index.ts'),
  skeleton: path.resolve(__dirname, './src/base/skeleton/index.ts'),
  tooltip: path.resolve(__dirname, './src/base/tooltip/index.ts'),
  editor: path.resolve(__dirname, './src/custom/editor/ui/editor.ts')
};

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    // replace({
    //   values: {
    //     'Object.defineProperty(exports': 'Object.defineProperty({}'
    //   },
    //   preventAssignment: false
    // }),
    svelte()
  ],
  build: {
    outDir: 'dist',
    lib: {
      entry,
      fileName: (format, entryName) => `js/${entryName}.${format}`
    },
    rollupOptions: {
      external: ['svelte'],
      output: {
        globals: {
          svelte: 'Svelte'
        }
      }
    }
  },
  resolve: {
    alias: {
      $src: path.resolve(__dirname, './src')
    }
  }
});
