import {
  BoldCourseLanding,
  BoldLandingHero,
  BoldLandingNav,
  BoldLandingPage,
  BoldLearningPathLanding,
  ClassicCourseLanding,
  ClassicLandingHero,
  ClassicLandingNav,
  ClassicLandingPage,
  ClassicLearningPathLanding,
  CorporateCourseLanding,
  CorporateLandingHero,
  CorporateLandingNav,
  CorporateLandingPage,
  CorporateLearningPathLanding,
  EditorialCourseLanding,
  EditorialLandingHero,
  EditorialLandingNav,
  EditorialLandingPage,
  EditorialLearningPathLanding,
  MinimalCourseLanding,
  MinimalLandingHero,
  MinimalLandingNav,
  MinimalLandingPage,
  MinimalLearningPathLanding,
  SaasCourseLanding,
  SaasLandingHero,
  SaasLandingNav,
  SaasLandingPage,
  SaasLearningPathLanding,
  StudioCourseLanding,
  StudioLandingHero,
  StudioLandingNav,
  StudioLandingPage,
  StudioLearningPathLanding,
  TechCourseLanding,
  TechLandingHero,
  TechLandingNav,
  TechLandingPage,
  TechLearningPathLanding,
  TerminalCourseLanding,
  TerminalLandingHero,
  TerminalLandingNav,
  TerminalLandingPage,
  TerminalLearningPathLanding,
  QuartzCourseLanding,
  QuartzLandingHero,
  QuartzLandingNav,
  QuartzLandingPage,
  QuartzLearningPathLanding,
  VibrantCourseLanding,
  VibrantLandingHero,
  VibrantLandingNav,
  VibrantLandingPage,
  VibrantLearningPathLanding
} from '@cio/ui/custom/org-landing-page';

export const landingPageThemeComponents = {
  minimal: MinimalLandingPage,
  bold: BoldLandingPage,
  classic: ClassicLandingPage,
  saas: SaasLandingPage,
  tech: TechLandingPage,
  studio: StudioLandingPage,
  corporate: CorporateLandingPage,
  terminal: TerminalLandingPage,
  editorial: EditorialLandingPage,
  vibrant: VibrantLandingPage,
  quartz: QuartzLandingPage
} as const;

export const courseLandingPageThemeComponents = {
  minimal: MinimalCourseLanding,
  bold: BoldCourseLanding,
  classic: ClassicCourseLanding,
  saas: SaasCourseLanding,
  tech: TechCourseLanding,
  studio: StudioCourseLanding,
  corporate: CorporateCourseLanding,
  terminal: TerminalCourseLanding,
  editorial: EditorialCourseLanding,
  vibrant: VibrantCourseLanding,
  quartz: QuartzCourseLanding
} as const;

export const learningPathLandingPageThemeComponents = {
  minimal: MinimalLearningPathLanding,
  bold: BoldLearningPathLanding,
  classic: ClassicLearningPathLanding,
  saas: SaasLearningPathLanding,
  tech: TechLearningPathLanding,
  studio: StudioLearningPathLanding,
  corporate: CorporateLearningPathLanding,
  terminal: TerminalLearningPathLanding,
  editorial: EditorialLearningPathLanding,
  vibrant: VibrantLearningPathLanding,
  quartz: QuartzLearningPathLanding
} as const;

export const landingPageNavComponents = {
  minimal: MinimalLandingNav,
  bold: BoldLandingNav,
  classic: ClassicLandingNav,
  saas: SaasLandingNav,
  tech: TechLandingNav,
  studio: StudioLandingNav,
  corporate: CorporateLandingNav,
  terminal: TerminalLandingNav,
  editorial: EditorialLandingNav,
  vibrant: VibrantLandingNav,
  quartz: QuartzLandingNav
} as const;

export const landingPageHeroComponents = {
  minimal: MinimalLandingHero,
  bold: BoldLandingHero,
  classic: ClassicLandingHero,
  saas: SaasLandingHero,
  tech: TechLandingHero,
  studio: StudioLandingHero,
  corporate: CorporateLandingHero,
  terminal: TerminalLandingHero,
  editorial: EditorialLandingHero,
  vibrant: VibrantLandingHero,
  quartz: QuartzLandingHero
} as const;
