/**
 * Packages `blume build` output for the assets-only Cloudflare Worker.
 *
 * `deployment.base: '/help'` makes Blume emit URLs like `/help/foo`, but it
 * does NOT nest the output — pages land in `dist/foo/index.html`. The worker
 * is asked for `/help/foo` (the website proxies the full path through), so
 * the build is moved under `build/help/` to line up with the served paths.
 *
 * `_redirects` written the same way apps/docs/scripts/package-assets.mjs does
 * — under a `base`, Astro prefixes a redirect's source but not its target, so
 * Astro's own `redirects` config is unusable here.
 */
import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');
const out = resolve(root, 'build');

const REDIRECTS = `# Generated by scripts/package-assets.mjs — do not edit.
/help/build-a-course/* /help/create-and-deliver/:splat 301
/help/live-classes/* /help/create-and-deliver/:splat 301
/help/enrollment-and-students/* /help/manage-students/:splat 301
/help/publish-your-academy/* /help/publish-and-brand/:splat 301
/help/organization-and-team/enterprise-sso-setup /help/integrations/enterprise-sso-setup 301
/help/organization-and-team/use-the-community-forum /help/integrations/use-the-community-forum 301
`;

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

await cp(dist, resolve(out, 'help'), { recursive: true });
await writeFile(resolve(out, '_redirects'), REDIRECTS);

console.log('[help] Packaged dist/ -> build/help/ with _redirects');
