create table
  public.lesson_language (
    id bigint generated by default as identity,
    lang text null,
    content text null,
    lesson_id uuid null default gen_random_uuid (),
    constraint lesson_language_pkey primary key (id),
    constraint public_lesson_language_lesson_id_fkey foreign key (lesson_id) references lesson (id)
  ) tablespace pg_default;