
create table "public"."template" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "description" text,
    "questionnaire" jsonb default '[]'::jsonb
);


alter table "public"."template" enable row level security;

CREATE UNIQUE INDEX template_pkey ON public.template USING btree (id);

alter table "public"."template" add constraint "template_pkey" PRIMARY KEY using index "template_pkey";

grant delete on table "public"."template" to "anon";

grant insert on table "public"."template" to "anon";

grant references on table "public"."template" to "anon";

grant select on table "public"."template" to "anon";

grant trigger on table "public"."template" to "anon";

grant truncate on table "public"."template" to "anon";

grant update on table "public"."template" to "anon";

grant delete on table "public"."template" to "authenticated";

grant insert on table "public"."template" to "authenticated";

grant references on table "public"."template" to "authenticated";

grant select on table "public"."template" to "authenticated";

grant trigger on table "public"."template" to "authenticated";

grant truncate on table "public"."template" to "authenticated";

grant update on table "public"."template" to "authenticated";

grant delete on table "public"."template" to "service_role";

grant insert on table "public"."template" to "service_role";

grant references on table "public"."template" to "service_role";

grant select on table "public"."template" to "service_role";

grant trigger on table "public"."template" to "service_role";

grant truncate on table "public"."template" to "service_role";

grant update on table "public"."template" to "service_role";