export const PLAN = {
  BASIC: 'BASIC',
  EARLY_ADOPTER: 'EARLY_ADOPTER',
  ENTERPRISE: 'ENTERPRISE'
};

export const PLAN_NAMES = {
  [PLAN.BASIC]: 'Free',
  [PLAN.EARLY_ADOPTER]: 'Early Adopter',
  [PLAN.ENTERPRISE]: 'Enterprise',
}

export const FEATURES = {
  BACIC_STUDENTS_50: 'BACIC_STUDENTS_50',
  EA_STUDENTS_10000: 'EA_STUDENTS_10000',
  EA_VIDEO_UPLOAD: 'EA_VIDEO_UPLOAD',
  EA_CERTIFICATE: 'EA_CERTIFICATE',
  EA_UPCOMING_FEATURES: 'EA_UPCOMING_FEATURES',
  ENTERPRISE_STUDENTS_UNLIMITED: 'ENTERPRISE_STUDENTS_UNLIMITED',
  ENTERPRISE_CUSTOM_DOMAIN: 'ENTERPRISE_CUSTOM_DOMAIN'
};

export const BASIC_FEATURES = [FEATURES.BACIC_STUDENTS_50];

export const EARYL_ADOPTER_FEATURES = [
  ...BASIC_FEATURES,
  FEATURES.EA_STUDENTS_10000,
  FEATURES.EA_VIDEO_UPLOAD,
  FEATURES.EA_CERTIFICATE,
  FEATURES.EA_UPCOMING_FEATURES
];

export const ENTERPRISE_FEATURES = [
  ...EARYL_ADOPTER_FEATURES,
  FEATURES.ENTERPRISE_STUDENTS_UNLIMITED,
  FEATURES.ENTERPRISE_CUSTOM_DOMAIN
];

export const PLANS_BY_FEATURE = {
  [PLAN.BASIC]: BASIC_FEATURES,
  [PLAN.EARLY_ADOPTER]: EARYL_ADOPTER_FEATURES,
  [PLAN.ENTERPRISE]: ENTERPRISE_FEATURES
};