import type { LandingThemeVars } from '../theme-vars-base';

export const vars: LandingThemeVars = {
  '--landing-bg': '#06070a',
  '--landing-bg-section': '#0c0e13',
  '--landing-card': '#0f1218',
  '--landing-card-soft': '#14171f',
  '--landing-fg': '#e9eaed',
  '--landing-fg-muted': '#9da1ab',
  '--landing-fg-faint': '#61656f',
  '--landing-border': '#1c1f28',
  '--landing-border-soft': '#161922',
  '--landing-accent': 'var(--primary)',
  '--landing-accent-fg': 'var(--primary-foreground)',
  '--landing-button-primary-bg': '#f4f5f7',
  '--landing-button-primary-fg': '#0a0b0e',
  '--landing-button-primary-bg-hover': '#ffffff',
  '--landing-button-secondary-bg': 'rgba(255,255,255,0.04)',
  '--landing-button-secondary-fg': '#e9eaed',
  '--landing-button-secondary-border': '#262a35',
  '--landing-button-secondary-bg-hover': 'rgba(255,255,255,0.08)',
  '--landing-button-tertiary-fg': 'var(--primary)',
  '--landing-button-tertiary-bg-hover': 'rgba(255,255,255,0.06)',
  '--landing-heading-weight': '600',
  '--landing-heading-tracking': 'normal',
  '--landing-heading-case': 'none',
  '--landing-eyebrow-tracking': '0.12em',
  '--landing-eyebrow-case': 'uppercase',
  '--landing-radius-card': '14px',
  '--landing-radius-pill': '9999px',
  '--landing-shadow-card': 'none',
  '--landing-divider': '1px solid #1a1c22',
  '--landing-mono-family': 'ui-monospace, "JetBrains Mono", "Fira Code", monospace',
  '--landing-glow': '0 0 12px color-mix(in oklab, var(--landing-accent), transparent 30%)',
  '--landing-panel-bg-accent': 'color-mix(in oklab, var(--landing-accent), #06070a 88%)'
};
