export const NAV_IDS = {
  NEWS_FEED: 'NEWS_FEED',
  LESSONS: 'LESSONS',
  COURSES: 'COURSES',
  ATTENDANCE: 'ATTENDANCE',
  SUBMISSIONS: 'SUBMISSIONS',
  MARKS: 'MARKS',
  CERTIFICATES: 'CERTIFICATES',
  LANDING_PAGE: 'LANDING_PAGE',
  PEOPLE: 'PEOPLE',
  SETTINGS: 'SETTINGS',
  SECTION: 'SECTION'
};
